export const PERMISSIONS = Object.freeze({
  DASHBOARD_VIEW: "DASHBOARD_VIEW",

  CUSTOMER_VIEW: "CUSTOMER_VIEW",
  CUSTOMER_CREATE: "CUSTOMER_CREATE",
  CUSTOMER_UPDATE: "CUSTOMER_UPDATE",
  CUSTOMER_DELETE: "CUSTOMER_DELETE",

  SUPPLIER_VIEW: "SUPPLIER_VIEW",
  SUPPLIER_CREATE: "SUPPLIER_CREATE",
  SUPPLIER_UPDATE: "SUPPLIER_UPDATE",
  SUPPLIER_DELETE: "SUPPLIER_DELETE",

  CATEGORY_VIEW: "CATEGORY_VIEW",
  CATEGORY_CREATE: "CATEGORY_CREATE",
  CATEGORY_UPDATE: "CATEGORY_UPDATE",
  CATEGORY_DELETE: "CATEGORY_DELETE",

  PRODUCT_VIEW: "PRODUCT_VIEW",
  PRODUCT_CREATE: "PRODUCT_CREATE",
  PRODUCT_UPDATE: "PRODUCT_UPDATE",
  PRODUCT_DELETE: "PRODUCT_DELETE",

  SALE_VIEW: "SALE_VIEW",
  SALE_CREATE: "SALE_CREATE",
  SALE_UPDATE: "SALE_UPDATE",
  SALE_CANCEL: "SALE_CANCEL",
  SALE_REFUND: "SALE_REFUND",

  PAYMENT_VIEW: "PAYMENT_VIEW",
  PAYMENT_CREATE: "PAYMENT_CREATE",
  PAYMENT_REFUND: "PAYMENT_REFUND",

  EXPENSE_VIEW: "EXPENSE_VIEW",
  EXPENSE_CREATE: "EXPENSE_CREATE",
  EXPENSE_UPDATE: "EXPENSE_UPDATE",
  EXPENSE_CANCEL: "EXPENSE_CANCEL",

  STOCK_VIEW: "STOCK_VIEW",
  STOCK_ADJUST: "STOCK_ADJUST",

  REPORT_VIEW: "REPORT_VIEW",

  STAFF_VIEW: "STAFF_VIEW",
  STAFF_INVITE: "STAFF_INVITE",
  STAFF_UPDATE: "STAFF_UPDATE",
  STAFF_SUSPEND: "STAFF_SUSPEND",

  BUSINESS_SETTINGS_VIEW: "BUSINESS_SETTINGS_VIEW",
  BUSINESS_SETTINGS_UPDATE: "BUSINESS_SETTINGS_UPDATE",
});

const ALL_PERMISSIONS = Object.values(PERMISSIONS);

const MANAGER_PERMISSIONS = [
  PERMISSIONS.DASHBOARD_VIEW,

  PERMISSIONS.CUSTOMER_VIEW,
  PERMISSIONS.CUSTOMER_CREATE,
  PERMISSIONS.CUSTOMER_UPDATE,

  PERMISSIONS.SUPPLIER_VIEW,
  PERMISSIONS.SUPPLIER_CREATE,
  PERMISSIONS.SUPPLIER_UPDATE,

  PERMISSIONS.CATEGORY_VIEW,
  PERMISSIONS.CATEGORY_CREATE,
  PERMISSIONS.CATEGORY_UPDATE,

  PERMISSIONS.PRODUCT_VIEW,
  PERMISSIONS.PRODUCT_CREATE,
  PERMISSIONS.PRODUCT_UPDATE,

  PERMISSIONS.SALE_VIEW,
  PERMISSIONS.SALE_CREATE,
  PERMISSIONS.SALE_UPDATE,
  PERMISSIONS.SALE_CANCEL,

  PERMISSIONS.PAYMENT_VIEW,
  PERMISSIONS.PAYMENT_CREATE,

  PERMISSIONS.EXPENSE_VIEW,
  PERMISSIONS.EXPENSE_CREATE,
  PERMISSIONS.EXPENSE_UPDATE,

  PERMISSIONS.STOCK_VIEW,
  PERMISSIONS.STOCK_ADJUST,

  PERMISSIONS.REPORT_VIEW,

  PERMISSIONS.STAFF_VIEW,

  PERMISSIONS.BUSINESS_SETTINGS_VIEW,
];

const STAFF_PERMISSIONS = [
  PERMISSIONS.DASHBOARD_VIEW,

  PERMISSIONS.CUSTOMER_VIEW,
  PERMISSIONS.CUSTOMER_CREATE,
  PERMISSIONS.CUSTOMER_UPDATE,

  PERMISSIONS.SUPPLIER_VIEW,

  PERMISSIONS.CATEGORY_VIEW,

  PERMISSIONS.PRODUCT_VIEW,

  PERMISSIONS.SALE_VIEW,
  PERMISSIONS.SALE_CREATE,

  PERMISSIONS.PAYMENT_VIEW,
  PERMISSIONS.PAYMENT_CREATE,

  PERMISSIONS.EXPENSE_VIEW,
  PERMISSIONS.EXPENSE_CREATE,

  PERMISSIONS.STOCK_VIEW,
];

const CASHIER_PERMISSIONS = [
  PERMISSIONS.DASHBOARD_VIEW,

  PERMISSIONS.CUSTOMER_VIEW,
  PERMISSIONS.CUSTOMER_CREATE,

  PERMISSIONS.PRODUCT_VIEW,

  PERMISSIONS.SALE_VIEW,
  PERMISSIONS.SALE_CREATE,

  PERMISSIONS.PAYMENT_VIEW,
  PERMISSIONS.PAYMENT_CREATE,

  PERMISSIONS.STOCK_VIEW,
];

export const ROLE_PERMISSIONS = Object.freeze({
  OWNER: new Set(ALL_PERMISSIONS),

  ADMIN: new Set(ALL_PERMISSIONS),

  MANAGER: new Set(MANAGER_PERMISSIONS),

  STAFF: new Set(STAFF_PERMISSIONS),

  CASHIER: new Set(CASHIER_PERMISSIONS),
});

export function roleHasPermission(role, permission) {
  const permissions = ROLE_PERMISSIONS[role];

  if (!permissions) {
    return false;
  }

  return permissions.has(permission);
}

export function getPermissionsForRole(role) {
  const permissions = ROLE_PERMISSIONS[role];

  if (!permissions) {
    return [];
  }

  return Array.from(permissions);
}
